version: '2'
services:
  buildbot:
    image: yezune/buildbot-master:latest
    volumes:
      - ./buildbot:/buildbot
      - ./srv:/srv
    environment:
      - BUILDBOT_CONFIG_DIR=config
#     - BUILDBOT_CONFIG_URL=https://github.com/buildbot/buildbot-docker-example-config/archive/master.tar.gz
      - BUILDBOT_WORKER_PORT=9989
      - BUILDBOT_WEB_URL=http://localhost:8010/
      - BUILDBOT_WEB_PORT=tcp:port=8010
        #user: buildbot
        #command: ["dumb-init","/usr/src/buildbot/start_buildbot.sh"]
    ports:
      - "8010:8010"
      - "9989:9989"

  janitor:
    image: yezune/buildbot-master:master
    volumes:
      - ./buildbot:/buildbot
      - ./srv:/srv
    command: ["dumb-init", "/buildbot/yocto-autobuilder-helper/janitor/ab-janitor"]

  worker:
    image: yezune/buildbot-worker:master
  
    volumes:
      - ./buildbot/yocto-autobuilder-helper:/buildbot/yocto-autobuilder-helper
  
    environment:
      - BUILDMASTER=buildbot
      - BUILDMASTER_PORT=9989
      - WORKERNAME=ubuntu2004-ty-1
      - WORKERPASS=pass
        #    links:
        # - buildbot
             
